---
#########################
#########################
## Deploy Docker Image ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

name: Release deployment

#######################################
# Start the job on all push to master #
#######################################
on:
  release:
    types: ['published']

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: job 1
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Start deployment       #
      ##########################
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: release
          desc: "depl_id: ${{ github.event.deployment.id }}, ref_id: ${{ github.head_ref }}"

     #############################
     # Init deployment variables #
     #############################
      - name: init deploymnet variables
        id: set_variables
        run: |
          echo ::set-output name=BUILD_RELEASE::${GITHUB_REF#refs/tags/}
          echo ::set-output name=BUILD_RELEASE_MAJOR::`echo ${GITHUB_REF%%.*} | awk -F/ '{ print v$3; }'`
          echo ::set-output name=BUILD_RELEASE_NUMBER::`echo ${GITHUB_REF#refs/tags/v}`
          echo ::set-output name=BUILD_DATE::`date -u +'%Y-%m-%dT%H:%M:%SZ'`
          echo ::set-output name=BUILD_REPO::$(echo ${GITHUB_REPOSITORY} | awk -F/ '{ print $2; }')
      - name: print deploymnet variables
        run: |
          echo $BUILD_RELEASE
          echo $BUILD_RELEASE_MAJOR
          echo $BUILD_RELEASE_NUMBER
          echo $BUILD_DATE
          echo $BUILD_REPO
        env:
          BUILD_RELEASE: ${{ steps.set_variables.outputs.BUILD_RELEASE }}
          BUILD_RELEASE_MAJOR: ${{ steps.set_variables.outputs.BUILD_RELEASE_MAJOR }}
          BUILD_RELEASE_NUMBER: ${{ steps.set_variables.outputs.BUILD_RELEASE_NUMBER }}
          BUILD_DATE: ${{ steps.set_variables.outputs.BUILD_DATE }}
          BUILD_REPO: ${{ steps.set_variables.outputs.BUILD_REPO }}

      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ########################
      # Setup Docker build X #
      ########################
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      ###############################
      # Login to DockerHub registry #
      ###############################
      #- name: Login to DockerHub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_USERNAME }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}

      ######################################
      # Login to GitHub Container registry #
      ######################################
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate swagger file
        run: |
          docker run -it --rm -v ${PWD}:/sss -w /sss quay.io/goswagger/swagger generate spec --scan-models -w /sss -o swagger.yaml
          ls -la

      ###########################################
      # Build and Push containers to registries #
      ###########################################
      - name: Build and push
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/actions/release-deployment/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
            BUILD_REPO=${{ steps.set_variables.outputs.BUILD_REPO }}
            BUILD_RELEASE_NUMBER=${{ steps.set_variables.outputs.BUILD_RELEASE_NUMBER }}
          target: app
          push: true
          tags: |
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-app:${{ steps.set_variables.outputs.BUILD_RELEASE }}
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-app:${{ steps.set_variables.outputs.BUILD_RELEASE_MAJOR }}
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-app:latest

      - name: Build and push
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./supplemental/docker/prod/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
            BUILD_REPO=${{ steps.set_variables.outputs.BUILD_REPO }}
            BUILD_RELEASE_NUMBER=${{ steps.set_variables.outputs.BUILD_RELEASE_NUMBER }}
          target: cron
          push: true
          tags: |
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-cron:${{ steps.set_variables.outputs.BUILD_RELEASE }}
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-cron:${{ steps.set_variables.outputs.BUILD_RELEASE_MAJOR }}
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-cron:latest

      - name: Build and push
        if: success()
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./supplemental/docker/prod/Dockerfile
          build-args: |
            BUILD_DATE=${{ env.BUILD_DATE }}
            BUILD_REVISION=${{ github.sha }}
            BUILD_VERSION=${{ github.sha }}
            BUILD_REPO=${{ steps.set_variables.outputs.BUILD_REPO }}
            BUILD_RELEASE_NUMBER=${{ steps.set_variables.outputs.BUILD_RELEASE_NUMBER }}
          target: uploaders
          push: true
          tags: |
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-uploaders:${{ steps.set_variables.outputs.BUILD_RELEASE }}
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-uploaders:${{ steps.set_variables.outputs.BUILD_RELEASE_MAJOR }}
            ghcr.io/ivankuchin/${{ steps.set_variables.outputs.BUILD_REPO }}-uploaders:latest

      ##########################
      # Stop deployment        #
      ##########################
      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

